package practice5.exceptions;
//Контрольный finally: Напишите метод с try-catch-finally, в котором finally выполняется даже при наличии return внутри try.
public class Finally {
    public static void main(String[] args) {

    }
}
